## PROUNI Data Processing

First, import the libraries

In [1]:
import sys
sys.path.append("../")
import pandas as pd
import src.util.file as file
import src.prouni.prouni as prouni
import src.data.data as dt
pd.set_option('display.float_format',lambda x: '%.0f' % x)

***

## Load the data tables

In [2]:
data_ies = file.load(file_path='../data/raw/dados_ies.csv',sep=',')
data_ies

,id_ies,nome,tipo_instituicao,rede,situacao_funcionamento,id_municipio,sigla_uf
0,1540,Instituto De Ensino Superior De Rondônia,Privada,Privada,Ativa,1100023,RO
1,4613,Centro Universitário Faema,Privada,Privada,Ativa,1100023,RO
2,10929,Faculdade Santo Andre,Privada,Privada,Ativa,1100049,RO
3,1209,Faculdade De Administracao De Empresas De Cacoal,Privada,Privada,Ativa,1100049,RO
4,1861,Faculdade De Direito De Cacoal,Privada,Privada,Ativa,1100049,RO
...,...,...,...,...,...,...,...
6584,4520,Faculdade Cenacap,Privada,Privada,Inativa,5300108,DF
6585,5284,Faculdade Para O Ensino Das Ciencias Juridicas...,Privada,Privada,Inativa,5300108,DF
6586,4923,Instituto Saber,Privada,Privada,Inativa,5300108,DF
6587,5030,Faculdade De Filosofia E Ciencias Do Planalto ...,Privada,Privada,Inativa,5300108,DF
6588,5042,Seminario Nacional Itej,Privada,Privada,Inativa,5300108,DF

In [3]:
prouni_dictionary = file.load(file_path='../data/raw/prouni_dicionario.csv',sep=',')
prouni_dictionary

,id_tabela,nome_coluna,chave,cobertura_temporal,valor
0,microdados,beneficiario_deficiente,0,(1),Não
1,microdados,sexo,1,(1),Feminino
2,microdados,beneficiario_deficiente,1,(1),Sim
3,microdados,raca_cor,1,(1),Amarela
4,microdados,modalidade_ensino,1,(1),Presencial
5,microdados,tipo_bolsa,1,(1),Integral
6,microdados,turno_curso,1,(1),Matutino
7,microdados,sexo,2,(1),Masculino
8,microdados,turno_curso,2,(1),Vespertino
9,microdados,tipo_bolsa,2,(1),Parcial (50%)
10,microdados,modalidade_ensino,2,(1),EAD
11,microdados,raca_cor,2,(1),Branca
12,microdados,raca_cor,3,(1),Indígena
13,microdados,tipo_bolsa,3,(1),Complementar (25%)
14,microdados,turno_curso,3,(1),Noturno
15,microdados,raca_cor,4,(1),Parda
16,microdados,turno_curso,4,(1),Integral
17,microdados,turno_curso,5,(1),Curso à Distancia
18,microdados,raca_cor,5,(1),Preta
19,microdados,raca_cor,6,(1),Não Informada

In [4]:
data_cities = file.load(file_path='../data/raw/dados_municipio.csv',sep=',')
data_cities

,id_municipio,id_municipio_6,id_municipio_tse,id_municipio_rf,id_municipio_bcb,nome,capital_uf,id_comarca,id_regiao_saude,nome_regiao_saude,...,nome_mesorregiao,id_regiao_metropolitana,nome_regiao_metropolitana,ddd,id_uf,sigla_uf,nome_uf,nome_regiao,amazonia_legal,centroide
0,5101837,510183,NaN,NaN,NaN,Boa Esperança do Norte,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,51,MT,Mato Grosso,Centro-Oeste,1,POINT(-54.9417429754238 -13.463197935201)
1,1100809,110080,477,681,46961,Candeias do Jamari,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-63.3254198532114 -8.88702392955617)
2,1100338,110033,434,47,44516,Nova Mamoré,0,1100106,11004,Madeira-Mamoré,...,Madeira-Guaporé,NaN,NaN,69,11,RO,Rondônia,Norte,1,POINT(-64.6295025002404 -10.3822863210755)
3,1100205,110020,35,3,30719,Porto Velho,1,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-64.3041357999869 -9.15394033687075)
4,1101104,110110,493,683,46851,Itapuã do Oeste,0,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,NaN,NaN,69,11,RO,Rondônia,Norte,1,POINT(-63.044960463046 -9.17019402601564)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5566,5209150,520915,92266,9799,43830,Gouvelândia,0,5218300,52017,Sul,...,Sul Goiano,NaN,NaN,64,52,GO,Goiás,Centro-Oeste,0,POINT(-50.1557720034523 -18.509097862386)
5567,5220405,522040,96059,9605,36799,São Simão,0,5220405,52015,Sudoeste I,...,Sul Goiano,NaN,NaN,64,52,GO,Goiás,Centro-Oeste,0,POINT(-50.5908964743097 -19.0104603156912)
5568,5216304,521630,94552,9455,24550,Paranaiguara,0,5216304,52015,Sudoeste I,...,Sul Goiano,NaN,NaN,64,52,GO,Goiás,Centro-Oeste,0,POINT(-50.6237723254387 -18.8084672995792)
5569,5218508,521850,95630,9563,4611,Quirinópolis,0,5218508,52015,Sudoeste I,...,Sul Goiano,NaN,NaN,64,52,GO,Goiás,Centro-Oeste,0,POINT(-50.5293403684736 -18.4373825773833)
5570,5300108,530010,97012,9701,35800,Brasília,1,5300108,53001,Distrito Federal,...,Distrito Federal,7801,Região Integrada de Desenvolvimento do Distrit...,61,53,DF,Distrito Federal,Centro-Oeste,0,POINT(-47.797310944881 -15.7808447891649)

In [5]:
data_prouni = file.load(file_path='../data/raw/dados_prouni.csv',sep=',',encoding='latin1')
data_prouni

,ano,sigla_uf,id_municipio,cpf,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,campus,nome_municipio_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino
0,2015,AP,1600303,***024922**,2,5,1966-11-12,0,1491,NaN,NaN,GEOGRAFIA,5,2,2
1,2015,AP,1600303,***978542**,2,4,1982-01-25,0,1491,NaN,NaN,PEDAGOGIA,5,1,2
2,2015,AP,1600303,***678932**,2,4,1970-04-09,0,322,NaN,NaN,GESTAO DA TECNOLOGIA DA INFORMACAO,5,1,2
3,2015,AP,1600303,***406412**,2,2,1993-05-31,0,322,NaN,NaN,ADMINISTRACAO,5,1,2
4,2015,AP,1600303,***867472**,2,4,1979-05-03,0,322,NaN,NaN,ADMINISTRACAO,5,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418692,2017,SP,3552809,***56821812**,1,4,1997-12-11,0,17854,NaN,NaN,PEDAGOGIA,1,1,1
1418693,2017,SP,3515004,***86830883**,1,2,1993-05-17,0,17854,NaN,NaN,PEDAGOGIA,3,1,1
1418694,2017,SP,3515004,***67219881**,1,2,1999-08-26,0,17854,NaN,NaN,ADMINISTRACAO,3,1,1
1418695,2017,SP,3552809,***31303827**,2,2,1999-01-24,0,17854,NaN,NaN,ENGENHARIA CIVIL,1,1,1
1418696,2017,SP,3525904,***98455655**,1,4,1999-03-16,0,17902,NaN,NaN,ADMINISTRACAO,3,2,1

***

Get the capital city of each state by filtering the rows where `capital_uf` is 1.

In [6]:
state_capital = prouni.get_state_capital(data_cities)
state_capital

,id_municipio,id_municipio_6,id_municipio_tse,id_municipio_rf,id_municipio_bcb,nome,capital_uf,id_comarca,id_regiao_saude,nome_regiao_saude,...,nome_mesorregiao,id_regiao_metropolitana,nome_regiao_metropolitana,ddd,id_uf,sigla_uf,nome_uf,nome_regiao,amazonia_legal,centroide
3,1100205,110020,35,3,30719,Porto Velho,1,1100205,11004,Madeira-Mamoré,...,Madeira-Guaporé,101,Região Metropolitana de Porto Velho,69,11,RO,Rondônia,Norte,1,POINT(-64.3041357999869 -9.15394033687075)
64,1200401,120040,1392,139,38955,Rio Branco,1,1200401,12002,Baixo Acre e Purus,...,Vale do Acre,NaN,NaN,68,12,AC,Acre,Norte,1,POINT(-68.3707905960881 -10.0661899239845)
109,1302603,130260,2550,255,5562,Manaus,1,1302603,13001,"Manaus, Entorno e Alto Rio Negro",...,Centro Amazonense,201,Região Metropolitana de Manaus,92,13,AM,Amazonas,Norte,1,POINT(-60.2596377045424 -2.62595709140444)
137,1400100,140010,3018,301,35295,Boa Vista,1,1400100,14001,Centro Norte,...,Norte de Roraima,301,Região Metropolitana da Capital,95,14,RR,Roraima,Norte,1,POINT(-60.7179908014411 3.11784589611939)
188,1501402,150140,4278,427,5816,Belém,1,1501402,15006,Metropolitana I,...,Metropolitana de Belém,601,Região Metropolitana de Belém,91,15,PA,Pará,Norte,1,POINT(-48.4598782458735 -1.240703177429)
303,1600303,160030,6050,605,28336,Macapá,1,1600303,16001,Área Central,...,Sul do Amapá,801,Região Metropolitana de Macapá,96,16,AP,Amapá,Norte,1,POINT(-50.7009098146547 0.555032538114925)
405,1721000,172100,73440,9733,45807,Palmas,1,1721000,17006,Capim Dourado,...,Oriental do Tocantins,901,Região Metropolitana de Palmas,63,17,TO,Tocantins,Norte,1,POINT(-48.1536047674387 -10.2185670577325)
467,2111300,211130,9210,921,37406,São Luís,1,2111300,21016,São Luís,...,Norte Maranhense,1101,Região Metropolitana da Grande São Luís,98,21,MA,Maranhão,Nordeste,1,POINT(-44.3072048527731 -2.63149283810468)
701,2211001,221100,12190,1219,11831,Teresina,1,2211001,22004,Entre Rios,...,Centro-Norte Piauiense,1301,Região Integrada de Desenvolvimento da Grande ...,86,22,PI,Piauí,Nordeste,0,POINT(-42.7406918788472 -5.10220717116497)
982,2304400,230440,13897,1389,34863,Fortaleza,1,2304400,23001,1ª Região Fortaleza,...,Metropolitana de Fortaleza,1401,Região Metropolitana de Fortaleza,85,23,CE,Ceará,Nordeste,0,POINT(-38.5277507942515 -3.78565110126041)
1230,2408102,240810,17612,1761,7735,Natal,1,2408102,24007,7ª Região de Saúde - Metropolitana,...,Leste Potiguar,1701,Região Metropolitana de Natal,84,24,RN,Rio Grande do Norte,Nordeste,0,POINT(-35.2287967247605 -5.80328556982982)
1456,2507507,250750,20516,2051,9087,João Pessoa,1,2507507,25001,1ª Região Mata Atlântica,...,Mata Paraibana,1801,Região Metropolitana de João Pessoa,83,25,PB,Paraíba,Nordeste,0,POINT(-34.8696766664414 -7.16546960455437)
1643,2611606,261160,25313,2531,24756,Recife,1,2611606,26010,Recife,...,Metropolitana de Recife,3001,Região Metropolitana de Recife,81,26,PE,Pernambuco,Nordeste,0,POINT(-34.933162526681 -8.03904274380255)
1736,2704302,270430,27855,2785,11257,Maceió,1,2704302,27001,1ª Região de Saúde,...,Leste Alagoano,3201,Região Metropolitana de Maceió,82,27,AL,Alagoas,Nordeste,0,POINT(-35.7103830237017 -9.52308171869148)
1812,2800308,280030,31054,3105,13530,Aracaju,1,2800308,28001,Aracaju,...,Leste Sergipano,4101,Região Metropolitana de Aracaju,79,28,SE,Sergipe,Nordeste,0,POINT(-37.0947653062458 -10.9940890881036)
2050,2927408,292740,38490,3849,1858,Salvador,1,2927408,29020,Salvador,...,Metropolitana de Salvador,4201,Região Metropolitana de Salvador,71,29,BA,Bahia,Nordeste,0,POINT(-38.5145680442897 -12.8734068282209)
2581,3106200,310620,41238,4123,24828,Belo Horizonte,1,3106200,31016,Belo Horizonte/ Nova Lima/ Caeté,...,Metropolitana de Belo Horizonte,4501,Região Metropolitana de Belo Horizonte,31,31,MG,Minas Gerais,Sudeste,0,POINT(-43.9598848641035 -19.9027207507742)
3144,3205309,320530,57053,5705,29665,Vitória,1,3205309,32002,Metropolitana,...,Central Espírito-santense,4701,Região Metropolitana da Grande Vitória,27,32,ES,Espírito Santo,Sudeste,0,POINT(-39.176338320945 -20.3338472806447)
3260,3304557,330455,60011,6001,3007,Rio de Janeiro,1,3304557,33005,Metropolitana I,...,Metropolitana do Rio de Janeiro,4801,Região Metropolitana do Rio de Janeiro,21,33,RJ,Rio de Janeiro,Sudeste,0,POINT(-43.4502267047878 -22.9233305427492)
3896,3550308,355030,71072,7107,7388,São Paulo,1,3550308,35016,São Paulo,...,Metropolitana de São Paulo,"4901, 4901, 4901, 4901, 4901","Região Metropolitana de São Paulo, Região Metr...",11,35,SP,São Paulo,Sudeste,0,POINT(-46.6480585579241 -23.649860314603)
4285,4106902,410690,75353,7535,13853,Curitiba,1,4106902,41002,2ª RS Metropolitana,...,Metropolitana de Curitiba,5501,Região Metropolitana de Curitiba,41,41,PR,Paraná,Sul,0,POINT(-49.288257976141 -25.4778625693795)
4553,4205407,420540,81051,8105,21216,Florianópolis,1,4205407,42007,Grande Florianópolis,...,Grande Florianópolis,6301,Região Metropolitana de Florianópolis,48,42,SC,Santa Catarina,Sul,0,POINT(-48.5080626776398 -27.5777806676493)
5013,4314902,431490,88013,8801,3681,Porto Alegre,1,4314902,43010,Região 10 - Capital e Vale do Gravataí,...,Metropolitana de Porto Alegre,7401,Região Metropolitana de Porto Alegre,51,43,RS,Rio Grande do Sul,Sul,0,POINT(-51.1651355343198 -30.0953153270686)
5121,5002704,500270,90514,9051,15026,Campo Grande,1,5002704,50001,Campo Grande,...,Centro Norte de Mato Grosso do Sul,NaN,NaN,67,50,MS,Mato Grosso do Sul,Centro-Oeste,0,POINT(-54.2509790105712 -20.9126206767924)
5297,5103403,510340,90670,9067,13918,Cuiabá,1,5103403,51002,Baixada Cuiabana,...,Centro-Sul Mato-grossense,7601,Região Metropolitana do Vale do Rio Cuiabá,65,51,MT,Mato Grosso,Centro-Oeste,1,POINT(-55.9391964604577 -15.4488555942925)
5440,5208707,520870,93734,9373,26242,Goiânia,1,5208707,52001,Central,...,Centro Goiano,7701,Região Metropolitana de Goiânia,62,52,GO,Goiás,Centro-Oeste,0,POINT(-49.2748108374863 -16.6430094188994)
5570,5300108,530010,97012,9701,35800,Brasília,1,5300108,53001,Distrito Federal,...,Distrito Federal,7801,Região Integrada de Desenvolvimento do Distrit...,61,53,DF,Distrito Federal,Centro-Oeste,0,POINT(-47.797310944881 -15.7808447891649)

***

## Check the data types of each table

In [7]:
print('IES table: \n')
print(data_ies.info())

print('\nDictionary table: \n')
print(prouni_dictionary.info())

print('\nCities table: \n')
print(data_cities.info())

print('\nProuni table: \n')
print(data_prouni.info())

IES table:

<class 'pandas.DataFrame'>
RangeIndex: 6589 entries, 0 to 6588
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_ies                  6589 non-null   int64
 1   nome                    6589 non-null   str
 2   tipo_instituicao        6589 non-null   str
 3   rede                    6589 non-null   str
 4   situacao_funcionamento  6589 non-null   str
 5   id_municipio            6589 non-null   int64
 6   sigla_uf                6589 non-null   str
dtypes: int64(2), str(5)
memory usage: 360.5 KB
None

Dictionary table:

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_tabela           20 non-null     str
 1   nome_coluna         20 non-null     str
 2   chave               20 non-null     int64
 3   cobertura_temporal  20 non-null     str
 4   valor               20 non-null     str
dtypes: int64(1), str(4)
memory usage: 932.0 bytes
None

Cities table:

<class 'pandas.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_municipio               5571 non-null   int64
 1   id_municipio_6             5571 non-null   int64
 2   id_municipio_tse           5570 non-null   float64
 3   id_municipio_rf            5570 non-null   float64
 4   id_municipio_bcb           5570 non-null   float64
 5   nome                       5571 non-null   str
 6   capital_uf                 5570 non-null   float64
 7   id_comarca                 5570 non-null   float64
 8   id_regiao_saude            5570 non-null   float64
 9   nome_regiao_saude          5570 non-null   str
 10  id_regiao_imediata         5571 non-null   int64
 11  nome_regiao_imediata       5571 non-null   str
 12  id_regiao_intermediaria    5571 non-null   int64
 13  nome_regiao_intermediaria  5571 non-null   str
 14  id_microrregiao            5570 non-null   float64
 15  nome_microrregiao          5570 non-null   str
 16  id_mesorregiao             5570 non-null   float64
 17  nome_mesorregiao           5570 non-null   str
 18  id_regiao_metropolitana    1432 non-null   str
 19  nome_regiao_metropolitana  1432 non-null   str
 20  ddd                        5570 non-null   float64
 21  id_uf                      5571 non-null   int64
 22  sigla_uf                   5571 non-null   str
 23  nome_uf                    5571 non-null   str
 24  nome_regiao                5571 non-null   str
 25  amazonia_legal             5571 non-null   int64
 26  centroide                  5571 non-null   str
dtypes: float64(9), int64(6), str(12)
memory usage: 1.1 MB
None

Prouni table:

<class 'pandas.DataFrame'>
RangeIndex: 1418697 entries, 0 to 1418696
Data columns (total 15 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   ano                      1418697 non-null  int64
 1   sigla_uf                 1418697 non-null  str
 2   id_municipio             1415046 non-null  float64
 3   cpf                      1418697 non-null  str
 4   sexo                     1418697 non-null  int64
 5   raca_cor                 1418697 non-null  int64
 6   data_nascimento          1418697 non-null  str
 7   beneficiario_deficiente  1418697 non-null  int64
 8   id_ies                   1418697 non-null  int64
 9   campus                   0 non-null        float64
 10  nome_municipio_ies       0 non-null        float64
 11  curso                    1418390 non-null  str
 12  turno_curso              1418697 non-null  int64
 13  tipo_bolsa               1418697 non-null  int64
 14  modalidade_ensino        1418697 non-null  int64
dtypes: float64(3), int64(8), str(4)
memory usage: 162.4 MB
None

***

### Check for missing values in each table

In [8]:
print('IES table: \n')
print(data_ies.isna().sum())

print('\nDictionary table: \n')
print(prouni_dictionary.isna().sum())

print('\nCities table: \n')
print(data_cities.isna().sum())

print('\nProuni table: \n')
print(data_prouni.isna().sum())

IES table:

id_ies                    0
nome                      0
tipo_instituicao          0
rede                      0
situacao_funcionamento    0
id_municipio              0
sigla_uf                  0
dtype: int64

Dictionary table:

id_tabela             0
nome_coluna           0
chave                 0
cobertura_temporal    0
valor                 0
dtype: int64

Cities table:

id_municipio                    0
id_municipio_6                  0
id_municipio_tse                1
id_municipio_rf                 1
id_municipio_bcb                1
nome                            0
capital_uf                      1
id_comarca                      1
id_regiao_saude                 1
nome_regiao_saude               1
id_regiao_imediata              0
nome_regiao_imediata            0
id_regiao_intermediaria         0
nome_regiao_intermediaria       0
id_microrregiao                 1
nome_microrregiao               1
id_mesorregiao                  1
nome_mesorregiao                1
id_regiao_metropolitana      4139
nome_regiao_metropolitana    4139
ddd                             1
id_uf                           0
sigla_uf                        0
nome_uf                         0
nome_regiao                     0
amazonia_legal                  0
centroide                       0
dtype: int64

Prouni table:

ano                              0
sigla_uf                         0
id_municipio                  3651
cpf                              0
sexo                             0
raca_cor                         0
data_nascimento                  0
beneficiario_deficiente          0
id_ies                           0
campus                     1418697
nome_municipio_ies         1418697
curso                          307
turno_curso                      0
tipo_bolsa                       0
modalidade_ensino                0
dtype: int64

***

## Fix missing values in the city column

If `id_municipio` is empty, fill it with the capital city of the student's state.

In [9]:
data_prouni = prouni.process_city_missing(data_prouni,state_capital)
data_prouni

,ano,sigla_uf,id_municipio,cpf,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,campus,nome_municipio_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino
0,2015,AP,1600303,***024922**,2,5,1966-11-12,0,1491,NaN,NaN,GEOGRAFIA,5,2,2
1,2015,AP,1600303,***978542**,2,4,1982-01-25,0,1491,NaN,NaN,PEDAGOGIA,5,1,2
2,2015,AP,1600303,***678932**,2,4,1970-04-09,0,322,NaN,NaN,GESTAO DA TECNOLOGIA DA INFORMACAO,5,1,2
3,2015,AP,1600303,***406412**,2,2,1993-05-31,0,322,NaN,NaN,ADMINISTRACAO,5,1,2
4,2015,AP,1600303,***867472**,2,4,1979-05-03,0,322,NaN,NaN,ADMINISTRACAO,5,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418692,2017,SP,3552809,***56821812**,1,4,1997-12-11,0,17854,NaN,NaN,PEDAGOGIA,1,1,1
1418693,2017,SP,3515004,***86830883**,1,2,1993-05-17,0,17854,NaN,NaN,PEDAGOGIA,3,1,1
1418694,2017,SP,3515004,***67219881**,1,2,1999-08-26,0,17854,NaN,NaN,ADMINISTRACAO,3,1,1
1418695,2017,SP,3552809,***31303827**,2,2,1999-01-24,0,17854,NaN,NaN,ENGENHARIA CIVIL,1,1,1
1418696,2017,SP,3525904,***98455655**,1,4,1999-03-16,0,17902,NaN,NaN,ADMINISTRACAO,3,2,1

***

## Remove irrelevant columns and process the data from the cities table

Remove the columns we don't need to keep the data clean.

In [10]:
columns = ['amazonia_legal', 'id_uf','ddd','nome_regiao_metropolitana', 'id_regiao_metropolitana', 'id_mesorregiao','nome_microrregiao','id_microrregiao', 'nome_regiao_intermediaria', 'id_regiao_intermediaria', 'nome_regiao_imediata', 'id_regiao_imediata','nome_regiao_saude', 'id_regiao_saude', 'id_comarca', 'id_municipio_bcb', 'id_municipio_rf','id_municipio_tse', 'id_municipio_6', 'nome_mesorregiao', 'centroide']
data_cities = dt.drop_columns(data_cities,columns)
data_cities

,id_municipio,nome,capital_uf,sigla_uf,nome_uf,nome_regiao
0,5101837,Boa Esperança do Norte,NaN,MT,Mato Grosso,Centro-Oeste
1,1100809,Candeias do Jamari,0,RO,Rondônia,Norte
2,1100338,Nova Mamoré,0,RO,Rondônia,Norte
3,1100205,Porto Velho,1,RO,Rondônia,Norte
4,1101104,Itapuã do Oeste,0,RO,Rondônia,Norte
...,...,...,...,...,...,...
5566,5209150,Gouvelândia,0,GO,Goiás,Centro-Oeste
5567,5220405,São Simão,0,GO,Goiás,Centro-Oeste
5568,5216304,Paranaiguara,0,GO,Goiás,Centro-Oeste
5569,5218508,Quirinópolis,0,GO,Goiás,Centro-Oeste
5570,5300108,Brasília,1,DF,Distrito Federal,Centro-Oeste

Check if any column has missing values.

In [11]:
data_missing = data_cities.isna().sum()
data_missing

id_municipio    0
nome            0
capital_uf      1
sigla_uf        0
nome_uf         0
nome_regiao     0
dtype: int64

Fill the missing `capital_uf` values with 0 (the city is not a capital).

In [12]:
data_cities['capital_uf'] = data_cities['capital_uf'].fillna(0.0)
data_cities

,id_municipio,nome,capital_uf,sigla_uf,nome_uf,nome_regiao
0,5101837,Boa Esperança do Norte,0,MT,Mato Grosso,Centro-Oeste
1,1100809,Candeias do Jamari,0,RO,Rondônia,Norte
2,1100338,Nova Mamoré,0,RO,Rondônia,Norte
3,1100205,Porto Velho,1,RO,Rondônia,Norte
4,1101104,Itapuã do Oeste,0,RO,Rondônia,Norte
...,...,...,...,...,...,...
5566,5209150,Gouvelândia,0,GO,Goiás,Centro-Oeste
5567,5220405,São Simão,0,GO,Goiás,Centro-Oeste
5568,5216304,Paranaiguara,0,GO,Goiás,Centro-Oeste
5569,5218508,Quirinópolis,0,GO,Goiás,Centro-Oeste
5570,5300108,Brasília,1,DF,Distrito Federal,Centro-Oeste

Convert the `capital_uf` values from numbers to text (1 → "sim", 0 → "não").

In [13]:
data_cities = prouni.change_data_capital(data_cities)
data_cities

,id_municipio,nome,capital_uf,sigla_uf,nome_uf,nome_regiao
0,5101837,Boa Esperança do Norte,não,MT,Mato Grosso,Centro-Oeste
1,1100809,Candeias do Jamari,não,RO,Rondônia,Norte
2,1100338,Nova Mamoré,não,RO,Rondônia,Norte
3,1100205,Porto Velho,sim,RO,Rondônia,Norte
4,1101104,Itapuã do Oeste,não,RO,Rondônia,Norte
...,...,...,...,...,...,...
5566,5209150,Gouvelândia,não,GO,Goiás,Centro-Oeste
5567,5220405,São Simão,não,GO,Goiás,Centro-Oeste
5568,5216304,Paranaiguara,não,GO,Goiás,Centro-Oeste
5569,5218508,Quirinópolis,não,GO,Goiás,Centro-Oeste
5570,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste

***

## Replace codes using the dictionary table

Some columns in the Prouni table have numeric codes. Replace these codes with their text values from the dictionary table.

In [14]:
data_prouni = prouni.process_column_dictionary(data_prouni,prouni_dictionary)
data_prouni

,ano,sigla_uf,id_municipio,cpf,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,campus,nome_municipio_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino
0,2015,AP,1600303,***024922**,Masculino,Preta,1966-11-12,Não,1491,NaN,NaN,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD
1,2015,AP,1600303,***978542**,Masculino,Parda,1982-01-25,Não,1491,NaN,NaN,PEDAGOGIA,Curso à Distancia,Integral,EAD
2,2015,AP,1600303,***678932**,Masculino,Parda,1970-04-09,Não,322,NaN,NaN,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD
3,2015,AP,1600303,***406412**,Masculino,Branca,1993-05-31,Não,322,NaN,NaN,ADMINISTRACAO,Curso à Distancia,Integral,EAD
4,2015,AP,1600303,***867472**,Masculino,Parda,1979-05-03,Não,322,NaN,NaN,ADMINISTRACAO,Curso à Distancia,Integral,EAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418692,2017,SP,3552809,***56821812**,Feminino,Parda,1997-12-11,Não,17854,NaN,NaN,PEDAGOGIA,Matutino,Integral,Presencial
1418693,2017,SP,3515004,***86830883**,Feminino,Branca,1993-05-17,Não,17854,NaN,NaN,PEDAGOGIA,Noturno,Integral,Presencial
1418694,2017,SP,3515004,***67219881**,Feminino,Branca,1999-08-26,Não,17854,NaN,NaN,ADMINISTRACAO,Noturno,Integral,Presencial
1418695,2017,SP,3552809,***31303827**,Masculino,Branca,1999-01-24,Não,17854,NaN,NaN,ENGENHARIA CIVIL,Matutino,Integral,Presencial
1418696,2017,SP,3525904,***98455655**,Feminino,Parda,1999-03-16,Não,17902,NaN,NaN,ADMINISTRACAO,Noturno,Parcial (50%),Presencial

***

### Drop the `cpf` column

It is personal data and we don't need it for the analysis.

In [15]:
data_prouni = data_prouni.drop(columns=['cpf'])
data_prouni

,ano,sigla_uf,id_municipio,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,campus,nome_municipio_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino
0,2015,AP,1600303,Masculino,Preta,1966-11-12,Não,1491,NaN,NaN,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD
1,2015,AP,1600303,Masculino,Parda,1982-01-25,Não,1491,NaN,NaN,PEDAGOGIA,Curso à Distancia,Integral,EAD
2,2015,AP,1600303,Masculino,Parda,1970-04-09,Não,322,NaN,NaN,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD
3,2015,AP,1600303,Masculino,Branca,1993-05-31,Não,322,NaN,NaN,ADMINISTRACAO,Curso à Distancia,Integral,EAD
4,2015,AP,1600303,Masculino,Parda,1979-05-03,Não,322,NaN,NaN,ADMINISTRACAO,Curso à Distancia,Integral,EAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418692,2017,SP,3552809,Feminino,Parda,1997-12-11,Não,17854,NaN,NaN,PEDAGOGIA,Matutino,Integral,Presencial
1418693,2017,SP,3515004,Feminino,Branca,1993-05-17,Não,17854,NaN,NaN,PEDAGOGIA,Noturno,Integral,Presencial
1418694,2017,SP,3515004,Feminino,Branca,1999-08-26,Não,17854,NaN,NaN,ADMINISTRACAO,Noturno,Integral,Presencial
1418695,2017,SP,3552809,Masculino,Branca,1999-01-24,Não,17854,NaN,NaN,ENGENHARIA CIVIL,Matutino,Integral,Presencial
1418696,2017,SP,3525904,Feminino,Parda,1999-03-16,Não,17902,NaN,NaN,ADMINISTRACAO,Noturno,Parcial (50%),Presencial

***

### Remove duplicate rows from the data

Check for duplicate rows in each table.

In [16]:
prouni_duplicate_count = data_prouni.duplicated().sum()
prouni_duplicate_count

np.int64(10539)

In [17]:
ies_duplicate_rows = data_ies.duplicated().sum()
ies_duplicate_rows

np.int64(0)

In [18]:
data_cities_duplicated_rows = data_cities.duplicated().sum()
data_cities_duplicated_rows

np.int64(0)

In [19]:
prouni_dictionary_duplicate_rows = prouni_dictionary.duplicated().sum()
prouni_dictionary_duplicate_rows

np.int64(0)

Remove duplicate rows from the Prouni data.

In [20]:
data_prouni = data_prouni.drop_duplicates()
data_prouni

,ano,sigla_uf,id_municipio,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,campus,nome_municipio_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino
0,2015,AP,1600303,Masculino,Preta,1966-11-12,Não,1491,NaN,NaN,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD
1,2015,AP,1600303,Masculino,Parda,1982-01-25,Não,1491,NaN,NaN,PEDAGOGIA,Curso à Distancia,Integral,EAD
2,2015,AP,1600303,Masculino,Parda,1970-04-09,Não,322,NaN,NaN,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD
3,2015,AP,1600303,Masculino,Branca,1993-05-31,Não,322,NaN,NaN,ADMINISTRACAO,Curso à Distancia,Integral,EAD
4,2015,AP,1600303,Masculino,Parda,1979-05-03,Não,322,NaN,NaN,ADMINISTRACAO,Curso à Distancia,Integral,EAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418692,2017,SP,3552809,Feminino,Parda,1997-12-11,Não,17854,NaN,NaN,PEDAGOGIA,Matutino,Integral,Presencial
1418693,2017,SP,3515004,Feminino,Branca,1993-05-17,Não,17854,NaN,NaN,PEDAGOGIA,Noturno,Integral,Presencial
1418694,2017,SP,3515004,Feminino,Branca,1999-08-26,Não,17854,NaN,NaN,ADMINISTRACAO,Noturno,Integral,Presencial
1418695,2017,SP,3552809,Masculino,Branca,1999-01-24,Não,17854,NaN,NaN,ENGENHARIA CIVIL,Matutino,Integral,Presencial
1418696,2017,SP,3525904,Feminino,Parda,1999-03-16,Não,17902,NaN,NaN,ADMINISTRACAO,Noturno,Parcial (50%),Presencial

***

## Prepare the join between the tables

Remove the `sigla_uf` column because it will come from the cities table after the join.

In [21]:

ies_drop_colums = ['sigla_uf']
data_ies = dt.drop_columns(data_ies, ies_drop_colums);
data_ies

,id_ies,nome,tipo_instituicao,rede,situacao_funcionamento,id_municipio
0,1540,Instituto De Ensino Superior De Rondônia,Privada,Privada,Ativa,1100023
1,4613,Centro Universitário Faema,Privada,Privada,Ativa,1100023
2,10929,Faculdade Santo Andre,Privada,Privada,Ativa,1100049
3,1209,Faculdade De Administracao De Empresas De Cacoal,Privada,Privada,Ativa,1100049
4,1861,Faculdade De Direito De Cacoal,Privada,Privada,Ativa,1100049
...,...,...,...,...,...,...
6584,4520,Faculdade Cenacap,Privada,Privada,Inativa,5300108
6585,5284,Faculdade Para O Ensino Das Ciencias Juridicas...,Privada,Privada,Inativa,5300108
6586,4923,Instituto Saber,Privada,Privada,Inativa,5300108
6587,5030,Faculdade De Filosofia E Ciencias Do Planalto ...,Privada,Privada,Inativa,5300108
6588,5042,Seminario Nacional Itej,Privada,Privada,Inativa,5300108

In [22]:

maps = {"id_municipio": "id_municipio"}
df_ies = dt.join_data(data_ies, data_cities, maps, join_type='inner')
df_ies

,id_ies,nome_x,tipo_instituicao,rede,situacao_funcionamento,id_municipio,nome_y,capital_uf,sigla_uf,nome_uf,nome_regiao
0,1540,Instituto De Ensino Superior De Rondônia,Privada,Privada,Ativa,1100023,Ariquemes,não,RO,Rondônia,Norte
1,4613,Centro Universitário Faema,Privada,Privada,Ativa,1100023,Ariquemes,não,RO,Rondônia,Norte
2,10929,Faculdade Santo Andre,Privada,Privada,Ativa,1100049,Cacoal,não,RO,Rondônia,Norte
3,1209,Faculdade De Administracao De Empresas De Cacoal,Privada,Privada,Ativa,1100049,Cacoal,não,RO,Rondônia,Norte
4,1861,Faculdade De Direito De Cacoal,Privada,Privada,Ativa,1100049,Cacoal,não,RO,Rondônia,Norte
...,...,...,...,...,...,...,...,...,...,...,...
6584,4520,Faculdade Cenacap,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6585,5284,Faculdade Para O Ensino Das Ciencias Juridicas...,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6586,4923,Instituto Saber,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6587,5030,Faculdade De Filosofia E Ciencias Do Planalto ...,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6588,5042,Seminario Nacional Itej,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste

Rename the columns of the IES table.

In [23]:
columns_rename = { 
    "nome_x" : "instituicao",
    "id_municipio" : "id_municipio_ies",
    "nome_y": "nome_municipio_ies",
    "capital_uf": "capital_uf_ies",
    "sigla_uf": "uf_ies",
    "nome_uf": "nome_uf_ies",
    "nome_regiao": "nome_regiao_ies"
}

df_ies = df_ies.rename(columns=columns_rename)
df_ies

,id_ies,instituicao,tipo_instituicao,rede,situacao_funcionamento,id_municipio_ies,nome_municipio_ies,capital_uf_ies,uf_ies,nome_uf_ies,nome_regiao_ies
0,1540,Instituto De Ensino Superior De Rondônia,Privada,Privada,Ativa,1100023,Ariquemes,não,RO,Rondônia,Norte
1,4613,Centro Universitário Faema,Privada,Privada,Ativa,1100023,Ariquemes,não,RO,Rondônia,Norte
2,10929,Faculdade Santo Andre,Privada,Privada,Ativa,1100049,Cacoal,não,RO,Rondônia,Norte
3,1209,Faculdade De Administracao De Empresas De Cacoal,Privada,Privada,Ativa,1100049,Cacoal,não,RO,Rondônia,Norte
4,1861,Faculdade De Direito De Cacoal,Privada,Privada,Ativa,1100049,Cacoal,não,RO,Rondônia,Norte
...,...,...,...,...,...,...,...,...,...,...,...
6584,4520,Faculdade Cenacap,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6585,5284,Faculdade Para O Ensino Das Ciencias Juridicas...,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6586,4923,Instituto Saber,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6587,5030,Faculdade De Filosofia E Ciencias Do Planalto ...,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste
6588,5042,Seminario Nacional Itej,Privada,Privada,Inativa,5300108,Brasília,sim,DF,Distrito Federal,Centro-Oeste

In [24]:
drop_columns = ['sigla_uf','campus', 'nome_municipio_ies']
data_prouni = dt.drop_columns(data_prouni, drop_columns)
data_prouni

,ano,id_municipio,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino
0,2015,1600303,Masculino,Preta,1966-11-12,Não,1491,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD
1,2015,1600303,Masculino,Parda,1982-01-25,Não,1491,PEDAGOGIA,Curso à Distancia,Integral,EAD
2,2015,1600303,Masculino,Parda,1970-04-09,Não,322,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD
3,2015,1600303,Masculino,Branca,1993-05-31,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,EAD
4,2015,1600303,Masculino,Parda,1979-05-03,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,EAD
...,...,...,...,...,...,...,...,...,...,...,...
1418692,2017,3552809,Feminino,Parda,1997-12-11,Não,17854,PEDAGOGIA,Matutino,Integral,Presencial
1418693,2017,3515004,Feminino,Branca,1993-05-17,Não,17854,PEDAGOGIA,Noturno,Integral,Presencial
1418694,2017,3515004,Feminino,Branca,1999-08-26,Não,17854,ADMINISTRACAO,Noturno,Integral,Presencial
1418695,2017,3552809,Masculino,Branca,1999-01-24,Não,17854,ENGENHARIA CIVIL,Matutino,Integral,Presencial
1418696,2017,3525904,Feminino,Parda,1999-03-16,Não,17902,ADMINISTRACAO,Noturno,Parcial (50%),Presencial

In [25]:
maps = {"id_municipio": "id_municipio"}
df_prouni = dt.join_data(data_prouni, data_cities, maps, join_type='inner')
df_prouni

,ano,id_municipio,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino,nome,capital_uf,sigla_uf,nome_uf,nome_regiao
0,2015,1600303,Masculino,Preta,1966-11-12,Não,1491,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD,Macapá,sim,AP,Amapá,Norte
1,2015,1600303,Masculino,Parda,1982-01-25,Não,1491,PEDAGOGIA,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
2,2015,1600303,Masculino,Parda,1970-04-09,Não,322,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
3,2015,1600303,Masculino,Branca,1993-05-31,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
4,2015,1600303,Masculino,Parda,1979-05-03,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408153,2017,3552809,Feminino,Parda,1997-12-11,Não,17854,PEDAGOGIA,Matutino,Integral,Presencial,Taboão da Serra,não,SP,São Paulo,Sudeste
1408154,2017,3515004,Feminino,Branca,1993-05-17,Não,17854,PEDAGOGIA,Noturno,Integral,Presencial,Embu das Artes,não,SP,São Paulo,Sudeste
1408155,2017,3515004,Feminino,Branca,1999-08-26,Não,17854,ADMINISTRACAO,Noturno,Integral,Presencial,Embu das Artes,não,SP,São Paulo,Sudeste
1408156,2017,3552809,Masculino,Branca,1999-01-24,Não,17854,ENGENHARIA CIVIL,Matutino,Integral,Presencial,Taboão da Serra,não,SP,São Paulo,Sudeste
1408157,2017,3525904,Feminino,Parda,1999-03-16,Não,17902,ADMINISTRACAO,Noturno,Parcial (50%),Presencial,Jundiaí,não,SP,São Paulo,Sudeste

In [26]:
columns_rename = { 
    "nome" : "cidade",
    "capital_uf" : "capital_estado",
    "nome_uf": "nome_estado",
    "sigla_uf": "uf"
}

df_prouni = df_prouni.rename(columns=columns_rename)
df_prouni

,ano,id_municipio,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,curso,turno_curso,tipo_bolsa,modalidade_ensino,cidade,capital_estado,uf,nome_estado,nome_regiao
0,2015,1600303,Masculino,Preta,1966-11-12,Não,1491,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD,Macapá,sim,AP,Amapá,Norte
1,2015,1600303,Masculino,Parda,1982-01-25,Não,1491,PEDAGOGIA,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
2,2015,1600303,Masculino,Parda,1970-04-09,Não,322,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
3,2015,1600303,Masculino,Branca,1993-05-31,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
4,2015,1600303,Masculino,Parda,1979-05-03,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,sim,AP,Amapá,Norte
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408153,2017,3552809,Feminino,Parda,1997-12-11,Não,17854,PEDAGOGIA,Matutino,Integral,Presencial,Taboão da Serra,não,SP,São Paulo,Sudeste
1408154,2017,3515004,Feminino,Branca,1993-05-17,Não,17854,PEDAGOGIA,Noturno,Integral,Presencial,Embu das Artes,não,SP,São Paulo,Sudeste
1408155,2017,3515004,Feminino,Branca,1999-08-26,Não,17854,ADMINISTRACAO,Noturno,Integral,Presencial,Embu das Artes,não,SP,São Paulo,Sudeste
1408156,2017,3552809,Masculino,Branca,1999-01-24,Não,17854,ENGENHARIA CIVIL,Matutino,Integral,Presencial,Taboão da Serra,não,SP,São Paulo,Sudeste
1408157,2017,3525904,Feminino,Parda,1999-03-16,Não,17902,ADMINISTRACAO,Noturno,Parcial (50%),Presencial,Jundiaí,não,SP,São Paulo,Sudeste

Join the Prouni and IES tables.

In [27]:
print(f'Prouni list counter befofe join: {len(data_prouni)}')

Prouni list counter befofe join: 1408158

In [28]:
maps = {"id_ies": "id_ies"}
df_prouni = dt.join_data(df_prouni, df_ies, maps, join_type='inner')
df_prouni

,ano,id_municipio,sexo,raca_cor,data_nascimento,beneficiario_deficiente,id_ies,curso,turno_curso,tipo_bolsa,...,instituicao,tipo_instituicao,rede,situacao_funcionamento,id_municipio_ies,nome_municipio_ies,capital_uf_ies,uf_ies,nome_uf_ies,nome_regiao_ies
0,2015,1600303,Masculino,Preta,1966-11-12,Não,1491,GEOGRAFIA,Curso à Distancia,Parcial (50%),...,Centro Universitário Internacional,Privada,Privada,Ativa,4106902,Curitiba,sim,PR,Paraná,Sul
1,2015,1600303,Masculino,Parda,1982-01-25,Não,1491,PEDAGOGIA,Curso à Distancia,Integral,...,Centro Universitário Internacional,Privada,Privada,Ativa,4106902,Curitiba,sim,PR,Paraná,Sul
2,2015,1600303,Masculino,Parda,1970-04-09,Não,322,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,...,Universidade Paulista,Privada,Privada,Ativa,3550308,São Paulo,sim,SP,São Paulo,Sudeste
3,2015,1600303,Masculino,Branca,1993-05-31,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,...,Universidade Paulista,Privada,Privada,Ativa,3550308,São Paulo,sim,SP,São Paulo,Sudeste
4,2015,1600303,Masculino,Parda,1979-05-03,Não,322,ADMINISTRACAO,Curso à Distancia,Integral,...,Universidade Paulista,Privada,Privada,Ativa,3550308,São Paulo,sim,SP,São Paulo,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408105,2017,3552809,Feminino,Parda,1997-12-11,Não,17854,PEDAGOGIA,Matutino,Integral,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,3552809,Taboão da Serra,não,SP,São Paulo,Sudeste
1408106,2017,3515004,Feminino,Branca,1993-05-17,Não,17854,PEDAGOGIA,Noturno,Integral,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,3552809,Taboão da Serra,não,SP,São Paulo,Sudeste
1408107,2017,3515004,Feminino,Branca,1999-08-26,Não,17854,ADMINISTRACAO,Noturno,Integral,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,3552809,Taboão da Serra,não,SP,São Paulo,Sudeste
1408108,2017,3552809,Masculino,Branca,1999-01-24,Não,17854,ENGENHARIA CIVIL,Matutino,Integral,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,3552809,Taboão da Serra,não,SP,São Paulo,Sudeste
1408109,2017,3525904,Feminino,Parda,1999-03-16,Não,17902,ADMINISTRACAO,Noturno,Parcial (50%),...,Faculdade Esamc Jundiaí,Privada,Privada,Ativa,3525904,Jundiaí,não,SP,São Paulo,Sudeste

In [29]:
print(f'Prouni list counter after join: {len(data_prouni)}')

Prouni list counter after join: 1408158

***

## Process the data and remove columns

Remove the columns we no longer need.

In [30]:
drop_columns = ['id_municipio', 'id_ies', 'id_municipio_ies']
df_prouni = dt.drop_columns(df_prouni, drop_columns)
df_prouni

,ano,sexo,raca_cor,data_nascimento,beneficiario_deficiente,curso,turno_curso,tipo_bolsa,modalidade_ensino,cidade,...,nome_regiao,instituicao,tipo_instituicao,rede,situacao_funcionamento,nome_municipio_ies,capital_uf_ies,uf_ies,nome_uf_ies,nome_regiao_ies
0,2015,Masculino,Preta,1966-11-12,Não,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD,Macapá,...,Norte,Centro Universitário Internacional,Privada,Privada,Ativa,Curitiba,sim,PR,Paraná,Sul
1,2015,Masculino,Parda,1982-01-25,Não,PEDAGOGIA,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Centro Universitário Internacional,Privada,Privada,Ativa,Curitiba,sim,PR,Paraná,Sul
2,2015,Masculino,Parda,1970-04-09,Não,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste
3,2015,Masculino,Branca,1993-05-31,Não,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste
4,2015,Masculino,Parda,1979-05-03,Não,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408105,2017,Feminino,Parda,1997-12-11,Não,PEDAGOGIA,Matutino,Integral,Presencial,Taboão da Serra,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408106,2017,Feminino,Branca,1993-05-17,Não,PEDAGOGIA,Noturno,Integral,Presencial,Embu das Artes,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408107,2017,Feminino,Branca,1999-08-26,Não,ADMINISTRACAO,Noturno,Integral,Presencial,Embu das Artes,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408108,2017,Masculino,Branca,1999-01-24,Não,ENGENHARIA CIVIL,Matutino,Integral,Presencial,Taboão da Serra,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408109,2017,Feminino,Parda,1999-03-16,Não,ADMINISTRACAO,Noturno,Parcial (50%),Presencial,Jundiaí,...,Sudeste,Faculdade Esamc Jundiaí,Privada,Privada,Ativa,Jundiaí,não,SP,São Paulo,Sudeste

Convert the `data_nascimento` column to the date type.

In [31]:
df_prouni['data_nascimento'] = pd.to_datetime(df_prouni['data_nascimento'], format='%Y-%m-%d')
df_prouni

,ano,sexo,raca_cor,data_nascimento,beneficiario_deficiente,curso,turno_curso,tipo_bolsa,modalidade_ensino,cidade,...,nome_regiao,instituicao,tipo_instituicao,rede,situacao_funcionamento,nome_municipio_ies,capital_uf_ies,uf_ies,nome_uf_ies,nome_regiao_ies
0,2015,Masculino,Preta,1966-11-12,Não,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD,Macapá,...,Norte,Centro Universitário Internacional,Privada,Privada,Ativa,Curitiba,sim,PR,Paraná,Sul
1,2015,Masculino,Parda,1982-01-25,Não,PEDAGOGIA,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Centro Universitário Internacional,Privada,Privada,Ativa,Curitiba,sim,PR,Paraná,Sul
2,2015,Masculino,Parda,1970-04-09,Não,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste
3,2015,Masculino,Branca,1993-05-31,Não,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste
4,2015,Masculino,Parda,1979-05-03,Não,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,...,Norte,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408105,2017,Feminino,Parda,1997-12-11,Não,PEDAGOGIA,Matutino,Integral,Presencial,Taboão da Serra,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408106,2017,Feminino,Branca,1993-05-17,Não,PEDAGOGIA,Noturno,Integral,Presencial,Embu das Artes,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408107,2017,Feminino,Branca,1999-08-26,Não,ADMINISTRACAO,Noturno,Integral,Presencial,Embu das Artes,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408108,2017,Masculino,Branca,1999-01-24,Não,ENGENHARIA CIVIL,Matutino,Integral,Presencial,Taboão da Serra,...,Sudeste,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste
1408109,2017,Feminino,Parda,1999-03-16,Não,ADMINISTRACAO,Noturno,Parcial (50%),Presencial,Jundiaí,...,Sudeste,Faculdade Esamc Jundiaí,Privada,Privada,Ativa,Jundiaí,não,SP,São Paulo,Sudeste

In [32]:
df_prouni.info()

<class 'pandas.DataFrame'>
RangeIndex: 1408110 entries, 0 to 1408109
Data columns (total 23 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   ano                      1408110 non-null  int64
 1   sexo                     1408110 non-null  str
 2   raca_cor                 1408110 non-null  str
 3   data_nascimento          1408110 non-null  datetime64[us]
 4   beneficiario_deficiente  1408110 non-null  str
 5   curso                    1407805 non-null  str
 6   turno_curso              1408110 non-null  str
 7   tipo_bolsa               1408110 non-null  str
 8   modalidade_ensino        1408110 non-null  str
 9   cidade                   1408110 non-null  str
 10  capital_estado           1408110 non-null  str
 11  uf                       1408110 non-null  str
 12  nome_estado              1408110 non-null  str
 13  nome_regiao              1408110 non-null  str
 14  instituicao              1408110 non-null  str
 15  tipo_instituicao         1408110 non-null  str
 16  rede                     1408110 non-null  str
 17  situacao_funcionamento   1408110 non-null  str
 18  nome_municipio_ies       1408110 non-null  str
 19  capital_uf_ies           1408110 non-null  str
 20  uf_ies                   1408110 non-null  str
 21  nome_uf_ies              1408110 non-null  str
 22  nome_regiao_ies          1408110 non-null  str
dtypes: datetime64[us](1), int64(1), str(21)
memory usage: 247.1 MB

Create a new column called `idade_candidato` with each candidate's age, calculated from `data_nascimento` and `ano` (the year the candidate applied to Prouni).

In [33]:
df_prouni['idade_candidato'] = df_prouni['ano'] - df_prouni['data_nascimento'].dt.year
df_prouni

,ano,sexo,raca_cor,data_nascimento,beneficiario_deficiente,curso,turno_curso,tipo_bolsa,modalidade_ensino,cidade,...,instituicao,tipo_instituicao,rede,situacao_funcionamento,nome_municipio_ies,capital_uf_ies,uf_ies,nome_uf_ies,nome_regiao_ies,idade_candidato
0,2015,Masculino,Preta,1966-11-12,Não,GEOGRAFIA,Curso à Distancia,Parcial (50%),EAD,Macapá,...,Centro Universitário Internacional,Privada,Privada,Ativa,Curitiba,sim,PR,Paraná,Sul,49
1,2015,Masculino,Parda,1982-01-25,Não,PEDAGOGIA,Curso à Distancia,Integral,EAD,Macapá,...,Centro Universitário Internacional,Privada,Privada,Ativa,Curitiba,sim,PR,Paraná,Sul,33
2,2015,Masculino,Parda,1970-04-09,Não,GESTAO DA TECNOLOGIA DA INFORMACAO,Curso à Distancia,Integral,EAD,Macapá,...,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste,45
3,2015,Masculino,Branca,1993-05-31,Não,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,...,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste,22
4,2015,Masculino,Parda,1979-05-03,Não,ADMINISTRACAO,Curso à Distancia,Integral,EAD,Macapá,...,Universidade Paulista,Privada,Privada,Ativa,São Paulo,sim,SP,São Paulo,Sudeste,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1408105,2017,Feminino,Parda,1997-12-11,Não,PEDAGOGIA,Matutino,Integral,Presencial,Taboão da Serra,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste,20
1408106,2017,Feminino,Branca,1993-05-17,Não,PEDAGOGIA,Noturno,Integral,Presencial,Embu das Artes,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste,24
1408107,2017,Feminino,Branca,1999-08-26,Não,ADMINISTRACAO,Noturno,Integral,Presencial,Embu das Artes,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste,18
1408108,2017,Masculino,Branca,1999-01-24,Não,ENGENHARIA CIVIL,Matutino,Integral,Presencial,Taboão da Serra,...,Centro Universitário Unifecaf,Privada,Privada,Ativa,Taboão da Serra,não,SP,São Paulo,Sudeste,18
1408109,2017,Feminino,Parda,1999-03-16,Não,ADMINISTRACAO,Noturno,Parcial (50%),Presencial,Jundiaí,...,Faculdade Esamc Jundiaí,Privada,Privada,Ativa,Jundiaí,não,SP,São Paulo,Sudeste,18

***

## Save the CSV file to the processed folder

After processing the data, save it as a new CSV file in the processed folder.

In [34]:
dt.save_csv(df_prouni, 'prouni_processed')

The CSV file salved in: /Users/jeisonpereira/dataScienteWorkspace/prouni-analytics/data/processed/prouni_processed.csv